### ISSUE TITLE
An additional `<` in the front.

### ISSUE THREAD

**Issue by liusida** [OTL/vscode-urdf#5]
Thanks for developing this handy tool. I don't know if I am the only one who likes to start every tag with a `<`, so to me I always need to delete the additional `<` once I have my block of code. :smile_cat: 

![Auto Complete](https://imgur.com/2qxnSlm.gif)

**Comment by OTL** [comment]
You don't need type `<` to use this snippets.
(I don't know that is a good behavior...)
